baseurl: /
languageCode: en-US
title: David Braun
theme: "quint"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: Publications
      url: /publications/
    - name: Projects
      url: https://twitter.com/rstudio
    - name: Contact
      url: https://google.com
params:
    MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
    MathJaxVersion: 2.7.5
    headliner: Hi, I'm Dave
    description: "Postdoc and aspiring data scientist. Published in neuroscience and population health. Happiest when I'm using cool stats stuff to solve meaningful problems."
    socials: 
        - name: Resume
          url: https://davebraun.net/resume
        - name: GitHub
          url: https://github.com/dbraun31
        - name: LinkedIn
          url: https://www.linkedin.com/in/david-braun-4468a979/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=ub5NLqcAAAAJ&hl=en&oi=sra
    favicon: favicon.ico
    contact: You can write me an [email](mailto:dbraun31@gmail.com).
    highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
    highlightjsLang:
        - r
        - yaml
    highlightjsTheme: github
    css: ['css/override.css']
    highlightjsVersion: 9.12.0
    logo:
        alt: Logo
        height: 50
        url: /logo.png
        width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: yes  # Enable syntax highlighting in fenced code blocks
    guessSyntax: yes  # Automatically detect the language if not specified
    style: "monokai"  # Choose a syntax highlighting theme (try "github", "dracula", "monokai", etc.)

